_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]


### voc.yml ###
num_classes: 6

TrainDataset:
  !VOCDataSet
    dataset_dir: E:/dataset/PCB_DATASET/ImageSets
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: E:/dataset/PCB_DATASET/ImageSets
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: E:/dataset/PCB_DATASET/ImageSets/label_list.txt


### runtime.yml ###
log_iter: 50
# Model save interval
snapshot_epoch: 5
save_dir: output


### ppyoloe_crn.yml ###
pretrain_weights: pretrain_weights/CSPResNetb_x_pretrained.pdparams
depth_mult: 1.33
width_mult: 1.25


### ppyoloe_reader.yml ###
TrainReader:
  batch_size: 4

LearningRate:
  base_lr: 0.00125
